# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-18 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='desc',
            new_name='content',
        ),
    ]
